#
# ---------- About Time Series Analysis ------------------------------------------------------------
#
ts_def <- "<p>
  <table width = 600 align=center>
    <tr><td><h3>Technical Analysis applied to Sentiment Time Series</h3></td></tr>
    <tr><td>
      <p>There are two basic kinds of analysis carried out on in finance (i.e. on securities / assets):</p>
      <ul><li>Fundamental Analysis</li>
          <li>Technical Analysis</li></ul>

      <p><u>Fundamental Analysis</u> - A method of evaluating a securities _intrinsic_ value by examining everything that can influence the value (e.g. overall economy, industry conditions, etc)</p>

      <p><u>Technical Analysis</u> - A method of evaluating securities by analyzing statistics generated by market activity (historical prices, volume, etc) using charts and pattern identification. i.e. _Only_ the charts are important and value is not thought to be intrinsic.</p>

      <p>A lot of finance deals with time series data. As a result a lot of time series analysis is rooted in finance and securities. Some methods, indicators, and patterns used in Technical Analysis may have appliability to non-financial time series data. This app demonstrates some approaches to identifying outliers, trends, trend reversal and momentum as applied to overall Tweet sentiment on three datasets.</p>




    </td></tr>
  </table>
  </p>
"






#
# ---------- SMA ------------------------------------------------------------
#
sma_def <- '<p><u>Simple Moving Average</u></p>
  <p> The average value over a sliding window of time. Short-term moving averages respond quickly to changes while longer-term moving averages are slow to react. The crossover points of two such moving average lines are trend and momentum indicators. </p>
  <p><u>Exponential Moving Average</u></p>
  <p>Similar to a simple moving average except more weight is given to recent data.'

sma_inter <- '<h3>Interpreting MA Crossover</h3>
  <p><u>asset-MA-crossover</u></p>
  <p>Plot a single MA line against the underlying pattern.</p>
  <p><b>cross below a MA line</b> - beginning of a downward trend.</p>
  <p><b>cross above a MA line</b> - beginning of an upward trend.</p>

  <p><u>MA-MA-crossover</u></p>
  <p>Plot two MA lines against the underlying pattern; one short term, one long term. In finance 50/100 or 50/200 is common, but some people use short periods such as 10/20 or 15/30.</p>
  <p><b>short crosses long MA from below</b> - a buy signal; upward trend reversal</p>
  <p><b>short above long MA</b> - upward trend signal; keep in</p>
  <p><b>short crosses long MA from above</b> - a sell signal, downward trend reversal</p>
  <p><b>long above short</b> - bearish signal; stay out of the market</p>

  <p><u>triple-crossover or MA-ribbon</u></p>
  <p>Draw 3 or more MA lines. Use additional MA lines to validate the signal given by others. e.g. plot 5/10/20 MA lines - the 5-day line cross over the others is taken as the primary signal with the 10-day cross over the 20-day line taken used as confirmation.</p>'



#
# ---------- IQR ------------------------------------------------------------
#
iqr_def <- "<p>Rob Hyndman's outlier detection method - remove non-stationarity in the time series, then find outliers in the residuals. The test for residual outliers is points greater than 1.5 Inter-Quartile Range (IQR) above or below the upper or lower quartiles. This implementation allows for adjusting the IQR multiplier.<p>"

iqr_inter <- '<h3>Interpreting IQR</h3>
  <p><b>Red Points</b> - data points more than 1.5 IQR above or below the upper or lower quartiles are identified as outliers and plotted in red. W. Huber suggests that in some cases 2.5 or even 3 times the IQR make a better threshold (e.g. in control chart methods) '




#
# ---------- Bollinger Bands ------------------------------------------------------------
#
bb_def <- "<p>Bollinger Bands are two lines plotted 2 standard deviations away from a simple moving average. It is one of the most popular techical analysis techniques (in finance). Bollinger said 88-89% of the 'action' shold take place between the bands, which makes moves near or outside the bands significant.</p>
  <p>Since standard deviation is a measure of volitility, Bollinger bands widen when the market becomes more volitile and contract during less volitile periods. </p>"

bb_inter <- "<h3>Interpreting Bollinger Bands</h3>
  <p><b>Red points</b> - Outliers - data points outside of the high/low bands
  <p><b>Wide bands</b> - volitility market</p>
  <p><b>Narrow bands</b> - less volitility</p>
  <p><b>Upper band</b> - A move near the upper band shows strength and also suggests the market is overbought. Prices are relatively high when at or above the upper band.</p>
  <p><b>Lower band</b> - A move near the lower band shows weakness and suggests the market is oversold. Prices are relatively low when at or below the lower band.</p>
  <p><b>M-Tops & W-bottoms</b> - Bollinger bands can be used to identify 'M-top' and 'W-bottom' patterns. M-tops (or double top) occurs during a bulling market and signals a downturn. W-bottoms form in a downtrend and signal an upward bounce.</p>"



#
# ---------- MACD ------------------------------------------------------------
#
macd_def <- 'Moving average convergence divergence (MACD) is a trend-following momentum indicator that shows the relationship between two moving averages of prices."
(Investopedia) A nine-day EMA of the MACD (called the signal line) is plotted on top of the MACD. The crossover of the two functions as a trigger for
buy and sell signals.'

macd_inter <- '<h3>Interpreting MACD</h3>
<p><b>Crossover</b> - When MACD falls below the signal line it is a bearish signal (sell). When MACD rises
above the signal line it is a bullish signal (buy)</p>
<p><b>Divergence</b> - When the observation diverges from the MACD it signals the end 
of the current trend.</p>
<p><b>Dramatic Rise</b> - When the MACD rises dramatically (i.e. the shorter MA 
pulls away from the longer MA) it signals the security is overbought and will soon return to normal levels</p>
<p><b>Zero line movement</b> - When the MACD is above zero the short term average is above 
the long term average, signalling upward momentum. (and vice versa) </p>'






#
# ---------- RSI ------------------------------------------------------------
#
rsi_def <- "<p>The relative strength index (RSI) is a very popular momentum indicator which compares the magnitude of recent gains and losses. RSI is used in technical analysis to indicate if an asset is overbought or oversold.</p>"

rsi_inter <- '<h3>Interpreting IQR</h3>
  <p><b>Above 70</b> - an asset is getting overvalued and may experience a pullback.</p>
  <p><b>Below 30</b> - an asset is likely to become undervalued</p>'






