---
title: "About Time Series Analysis"
output: html_document
---

# Technical Analysis

There are two basic kinds of analysis carried out on in finance (i.e. on securities / assets):
	- Fundamental Analysis
	- Technical Analysis

Fundamental Analysis - A method of evaluating a securities _intrinsic_ value by examining everything that can influence the value (e.g. overall economy, industry conditions, etc)

Technical Analysis - A method of evaluating securities by analyzing statistics generated by market activity (historical prices, volume, etc) using charts and pattern identification. i.e. _Only_ the charts are important and value is not thought to be intrinsic.

A lot of finance deals with time series data. As a result a lot of time series analysis is rooted in finance and securities. Some methods, indicators, and patterns used in Technical Analysis may have appliability to non-financial time series data. This app demonstrates some approaches to identifying outliers, trends, trend reversal and momentum as applied to overall Tweet sentiment on three datasets.

